### ISSUE TITLE
Allow to combine items to one dropdown menu

### ISSUE THREAD

**Issue by gsantner** [Curly-/Top-bar-script-executor#4]
Please add an option to combine all items into one dropdown menu (Displaying items in row layout with icon and title). I found no other extension yet allowing this, while having an easy editing ui for items.

**Comment by Curly-** [comment]
I don't use Gnome anymore, so this extension is no longer being developed. If you want this feature, you'll have to fork the project. Sorry about that.

**Comment by gsantner** [comment]
I can feel you
